### ISSUE TITLE
SOFTAP Error when connecting to the ESP32

### ISSUE THREAD

**Issue by williamesp2015** [espressif/arduino-esp32#2530]
### Hardware:
Board:							ESP32 Dev Module 
Core Installation version:			espressif32                     @ 1.7.0 UPTODATED
IDE name:						Arduino Platform.io

Computer OS:                                        Windows 10
PlatformIO 4.0.0a3
### Description:
esp32 Successfully run SOFTAP but when client is connecting to it error appears:
E (8854) event: mismatch or invalid event, id=63
E (8855) event: default event handler failed!
It seems new changes in the wifi.cpp

**Comment by me-no-dev** [comment]
fixed in Master already :)

**Comment by williamesp2015** [comment]
I just updated my platformIo code and libraries , even I deleted espriff32 directory but it did not solved

**Comment by danielfabro** [comment]
I have the same problem!
