### ISSUE TITLE
calling millis() in an interrupt service routine causes a panic

### ISSUE THREAD

**Issue by judge2005** [espressif/arduino-esp32#2758]
Compile and run the code below - you will get a panic in the serial monitor. This is surprising, given that millis() is tagged with IRAM_ATTR. If I call esp_timer_get_time(), there is no crash. I am using release 1.0.2

```cpp
#include "Arduino.h"
#include "esp_spi_flash.h"
#include "nvs.h"
#include "nvs_flash.h"

hw_timer_t *timer;

void IRAM_ATTR isr() {
	millis();
}

void setup() {
	Serial.begin(115200);

    nvs_flash_init();

    timer = timerBegin(0, 80, true); // timer_id = 0; divider=80; countUp = true; So at 80MHz, we have a granularity of 1MHz
	timerAttachInterrupt(timer, isr, true); // edge = true
	timerAlarmWrite(timer, 100, true); // Period = 100 micro seconds
	timerAlarmEnable(timer);
}

void loop() {
	const uint32_t n = SPI_FLASH_SEC_SIZE;
	uint32_t val_read;
	for (uint32_t offset = 0; offset < n; offset += 4) {
		if (spi_flash_read(offset, (uint8_t *) &val_read, 4) != ESP_OK) {
			break;
		}
	}

	delay(10);
}
```

**Comment by atanisoft** [comment]
> Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)

This line indicates that spi_flash disabled cache but something was accessed outside of the IRAM area. About the only thing I can think of is the 1000ULL but that should be compiled in as a constant. Can you try swapping millis() with micros() ?

Also try disabling the flash access in loop() (separate test) to confirm if that is playing a factor.

**Comment by judge2005** [comment]
micros() works. How do I disable flash access for the other test?

**Comment by atanisoft** [comment]
> micros() works. How do I disable flash access for the other test?

Interesting that micros() works but millis() doesn't.  @me-no-dev thoughts?

As for disabling flash access, comment out the code in loop(), specifically spi_flash_read()

**Comment by judge2005** [comment]
The whole point of the test is that I am accessing flash when the ISR happens. It works fine without the flash access.

I ran multiple tests with various local implementations of millis(). It looks like the result of the computation is being stored in cache ram(?) before it is returned. The only version that I could get to work is the below:

unsigned long IRAM_ATTR my_millis()
{
	DRAM_ATTR static int64_t m = esp_timer_get_time()/1000ULL;
            return (unsigned long) m;
}

I tried volatile variables for both the result of esp_timer_get_time() and the constant 1000ULL. I also tried a DRAM_ATTR static constant for 1000ULL. Nothing worked except the above code, which is clearly not ‘thread safe’ because it uses a static variable.

This has nasty implications for anything I want to use in an ISR.

**Comment by judge2005** [comment]
BTW, why is micros() a signed value? Won’t that cause issues with math when it rolls over?

**Comment by judge2005** [comment]
Actually, the static variable doesn’t need to be tagged with DRAM_ATTR.

**Comment by judge2005** [comment]
Except I think I just realized that it only works because the static variable is only set once. Ughhh.

**Comment by judge2005** [comment]
Ahhhh. I just tried something else that gave me the following compilation error:

..\newesp32test.ino:12:4: error: invalid operands of types 'int64_t {aka long long int}' and 'div_t(int, int)' to binary 'operator/'
  m /= div;
    ^
..\newesp32test.ino:12:4: error:   in evaluation of 'operator/=(int64_t {aka long long int}, struct div_t(int, int))'

So it looks like the division is actually calling a function to do the division. I guess that function lives in flash…

**Comment by judge2005** [comment]
It looks like this is because 64 bit divisions call a function (I tried a test which happened to give a compiler error that lead me to this conclusion).

> The GCC C compiler generates code that calls functions in the libgcc library to implement the / and  % operations with 64-bit operands on 32-bit CPUs

So, that function is not tagged with IRAM_ATTR and so is not safe to call from an ISR. I will figure out how to do this division myself - just need to the source to that library!

**Comment by stickbreaker** [comment]
As a work around you might use [TickType_t xTaskGetTickCountFromISR();](https://www.freertos.org/a00021.html#xTaskGetTickCountFromISR) TickType_t is a uint32_t

I use it in the I2C driver that runs in an Interrupt context and supports iCache disabled.

Chuck.

**Comment by judge2005** [comment]
Thanks @stickbreaker, I will look into that. To close the loop on this, it is definitely caused by GCC generating a call to a library. Possibly, if the optimization level was modified for speed, it might not do that. For your edification, here is some code that works - I'm not claiming it is pretty, but it might actually be faster than the GCC library version. The divs10 code is adapted from the 32 bit version [here](https://www.hackersdelight.org/divcMore.pdf). Adapting the divs1000 code in that paper to 64 bits is beyond me. Anyway, here is the code:
```cpp
#include "Arduino.h"
#include "esp_spi_flash.h"
#include "nvs.h"
#include "nvs_flash.h"

hw_timer_t *timer;

// Code adapted for 64 bits from https://www.hackersdelight.org/divcMore.pdf
int64_t IRAM_ATTR divs10(int64_t n) {
	int64_t q, r;
	n = n + (n >> 63 & 9);
	q = (n >> 1) + (n >> 2);
	q = q + (q >> 4);
	q = q + (q >> 8);
	q = q + (q >> 16);
	q = q + (q >> 32);
	q = q >> 3;
	r = n - q * 10;
	return q + ((r + 6) >> 4);
// return q + (r > 9);
}

int64_t IRAM_ATTR divs1000(int64_t n) {
	return divs10(divs10(divs10(n)));
}

unsigned long IRAM_ATTR my_millis()
{
	return divs1000(esp_timer_get_time());
}

void IRAM_ATTR isr() {
	my_millis();
}

void setup() {
	Serial.begin(115200);

	nvs_flash_init();

	timer = timerBegin(0, 80, true); // timer_id = 0; divider=80; countUp = true; So at 80MHz, we have a granularity of 1MHz
	timerAttachInterrupt(timer, isr, true);// edge = true
	timerAlarmWrite(timer, 100, true);// Period = 100 micro seconds
	timerAlarmEnable(timer);
}

void loop() {
	const uint32_t n = SPI_FLASH_SEC_SIZE;
	uint32_t val_read;
	for (uint32_t offset = 0; offset < n; offset += 4) {
		if (spi_flash_read(offset, (uint8_t *) &val_read, 4) != ESP_OK) {
			break;
		}
	}

	delay(10);
}
`

**Comment by me-no-dev** [comment]
done :)

**Comment by pknoe3lh** [comment]
This is still a problem for me! "Stable 1.0.2"
The function millis is in DRAM but the div(1000) is not. 
So when using it with Preference Library the ESP32 crashes:

`Guru Meditation Error: Core  1 panic'ed (Cache disabled but cached memory region accessed)
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalInstruction). Exception was unhandled.
Memory dump at 0x400f00f0: bad00bad bad00bad bad00bad
Guru Meditation Error: Core  1 panic'ed (IllegalIGuru Meditation Error: Core  1 panic'ed (Unhandled debug exception)
Debug exception reason: Stack canary watchpoint triggered (loopTask) 
`

**Comment by judge2005** [comment]
Works for me using latest. Maybe 1.0.3.

Another issue is: you can’t use switch statements in ISRs either.

**Comment by pknoe3lh** [comment]
Interesting ... Gcc can do a lot of unexpected thing!
The jump tables can be turned off by this flag:
gcc -g -v -fno-jump-tables SO.c
