### ISSUE TITLE
WiFi hostname set/get is not working correctly

### ISSUE THREAD

**Issue by miksumin** [espressif/arduino-esp32#4752]
### Hardware:
Board:							ESP32 Dev Module
Core Installation version:			1.0.5-rc1
IDE name:						Arduino IDE 1.8.7
Flash Frequency:					40Mhz
PSRAM enabled:                                    no
Upload Speed:					115200
Computer OS:                                        Windows 7

### Description:
Starting core version 1.0.5-rc1 and up to core version 1.0.5-rc6 WiFi hostname set/get is not working correctly.
Anything you set by calling WiFi.setHostname("Hostname") then you call WiFi.getHostname() and you get "espressif".

### Sketch:  (leave the backquotes for [code formatting](https://help.github.com/articles/creating-and-highlighting-code-blocks/))
```cpp

//Change the code below by your sketch
#include <Arduino.h>
#include <WiFi.h>

void setup() {
  WiFi.mode(WIFI_STA);
  WiFi.setHostname("Hostname");
  WiFi.begin(WIFI_SSID, WIFI_PASS);
    if (WiFi.status() == WL_CONNECTED) {
      Serial.println(WiFi.getHostname());
    }
}

void loop() {
}
```

### Debug Messages:
```
Enable Core debug level: Debug on tools menu of Arduino IDE, then put the serial output here 
```

**Comment by kapyaar** [comment]
Can you try 
WiFi.config(INADDR_NONE, INADDR_NONE, INADDR_NONE);
WiFi.setHostname("hostName");
//https://github.com/espressif/arduino-esp32/issues/2537#issuecomment-508558849

**Comment by me-no-dev** [comment]
This has been fixed here: https://github.com/espressif/arduino-esp32/commit/ad4cf1461bea3fb1378402b572383813ea9c2a06

next RC will have it

**Comment by Heisenberg2980** [comment]
@me-no-dev I am still having this issue. I am using Visual Studio Code, how can I check if my sketch is using the version of arduino-esp32 that contains that fix?

**Comment by me-no-dev** [comment]
@Heisenberg2980 any chance you can try this with github version of master instead?

**Comment by Heisenberg2980** [comment]
@me-no-dev what do you mean with "github version of master"?

**Comment by Heisenberg2980** [comment]
@me-no-dev thank you for the info, how do you know the version of the esp core I am using, is it inside of one of the libraries I mentioned? 
I am happy to wait a few days for the 2.0.3 to be out, but I am not sure what I will need to update to start using that version rather than 1.0.5-rc1

**Comment by me-no-dev** [comment]
Sorry @Heisenberg2980 I thought you also posted the issue and up there it's said that 1.0.5-rc1 is used. I do not know which version you are using. Updates happen through ArduinoIDE's board manager

**Comment by Heisenberg2980** [comment]
@me-no-dev right, the version I have in Arduino IDE is 1.0.4, but for this sketch I am using Visual Studio Code instead, and it is weird because I am not able to find the ESP32 library anywhere in Visual Studio Code, any idea where it could be hiding?

Regarding the Arduino IDE, do you know by any change why it is just offering me versions up to 1.0.6 and not the versions 2.0.0 and above that are available from August 2021 (https://github.com/espressif/arduino-esp32/releases)?
![image](https://user-images.githubusercontent.com/58039006/155175473-8f628b6f-cfc7-4731-9880-ce5192d40954.png)

**Comment by me-no-dev** [comment]
You are probably using the old json link that is no longer updated :)
Check here: https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html#installing-using-boards-manager

**Comment by Heisenberg2980** [comment]
@me-no-dev You are completely right!! version 2.0.2 installed now in Arduino IDE, thank you very much for your help.

I just need to figure out how to use it on my sketch in VS Code.
