### ISSUE TITLE
ESP32-C3 can not connect to WiFi AP (AUTH_EXPIRE)

### ISSUE THREAD

**Issue by XFer012** [espressif/arduino-esp32#6767]
### Board

Lolin C3-Mini

### Device Description

Lolin C3-Mini alone, nothing connected

### Hardware Configuration

Nothing

### Version

v2.0.3

### IDE Name

Arduino IDE 1.8.19

### Operating System

Windows 10 Pro 64 bit

### Flash frequency

80 MHz

### PSRAM enabled

no

### Upload speed

921600

### Description

ESP32-C3 can not connect to my AccessPoint, while ESP32 "stock" (ESP32 Devkit board) connects without issues

C3 reports continously "[W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE"

### Sketch

```cpp
/*
 *  This sketch sends data via HTTP GET requests to data.sparkfun.com service.
 *
 *  You need to get streamId and privateKey at data.sparkfun.com and paste them
 *  below. Or just customize this script to talk to other HTTP servers.
 *
 */

#include <WiFi.h>

const char* ssid     = "[my SSID]";
const char* password = "[my WPA2 password]";

const char* host = "data.sparkfun.com";
const char* streamId   = "....................";
const char* privateKey = "....................";

void setup()
{
    Serial.begin(115200);
    delay(10);

    // We start by connecting to a WiFi network

    Serial.println();
    Serial.println();
    Serial.print("Connecting to ");
    Serial.println(ssid);

    WiFi.begin(ssid, password);

    while (WiFi.status() != WL_CONNECTED) {
        delay(2000);
        Serial.print("Not connected. Status="); Serial.println(WiFi.status());
    }

    Serial.println("");
    Serial.println("WiFi connected");
    Serial.println("IP address: ");
    Serial.println(WiFi.localIP());
    delay(5000);
}

int value = 0;

void loop()
{
    delay(5000);
    ++value;

    Serial.print("connecting to ");
    Serial.println(host);

    // Use WiFiClient class to create TCP connections
    WiFiClient client;
    const int httpPort = 80;
    if (!client.connect(host, httpPort)) {
        Serial.println("connection failed");
        return;
    }

    // We now create a URI for the request
    String url = "/input/";
    url += streamId;
    url += "?private_key=";
    url += privateKey;
    url += "&value=";
    url += value;

    Serial.print("Requesting URL: ");
    Serial.println(url);

    // This will send the request to the server
    client.print(String("GET ") + url + " HTTP/1.1\r\n" +
                 "Host: " + host + "\r\n" +
                 "Connection: close\r\n\r\n");
    unsigned long timeout = millis();
    while (client.available() == 0) {
        if (millis() - timeout > 5000) {
            Serial.println(">>> Client Timeout !");
            client.stop();
            return;
        }
    }

    // Read all the lines of the reply from server and print them to Serial
    while(client.available()) {
        String line = client.readStringUntil('\r');
        Serial.print(line);
    }

    Serial.println();
    Serial.println("closing connection");
}
```

### Debug Message

```plain
[W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
```

### Other Steps to Reproduce

I also tried ESP32 Devkit board, same AP, same parameters, same position; works without issues 

### I have checked existing issues, online documentation and the Troubleshooting Guide

- [X] I confirm I have checked existing issues, online documentation and Troubleshooting guide.

**Comment by XFer012** [comment]
Full output from serial monitor:

`Connecting to CasaWiFi
[  1503][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Not connected. Status=6
[  2528][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[  3550][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Not connected. Status=6
[  4574][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[  5600][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Not connected. Status=6
[  6624][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[  7648][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Not connected. Status=6
[  8672][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[  9696][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
Not connected. Status=6
[ 10720][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
[ 11744][W][WiFiGeneric.cpp:873] _eventCallback(): Reason: 2 - AUTH_EXPIRE
`
[...]

**Comment by SuGlider** [comment]
@PilnyTomas, PTAL - Thanks!

**Comment by PilnyTomas** [comment]
Hi @XFer012, could you please get the signal strength of the AP you are trying to connect to?
You can use [WiFiScan example](https://github.com/espressif/arduino-esp32/blob/master/libraries/WiFi/examples/WiFiScan/WiFiScan.ino). You can also find it in Arduino IDE under File > Examples > WiFi > WiFiScan

**Comment by XFer012** [comment]
Sure, here it's the output from WiFiScan:

scan done
10 networks found
1: [My SSID] (-36)*     <--- this is mine
2: TP-Link_xxxx (-67)*
3: Vodafone-xxxx (-77)*
4: Vodafone-xxxx (-79)*
5: Vodafone-xxxx (-79) 
6: Vodafone-xxxx (-80) 
7: Vodafone-xxxx (-85) 
8: Vodafone-xxxx (-86) 
9: Vodafone-xxxx (-87)*
10: Vodafone-xxxx (-87)*

**Comment by Jason2866** [comment]
We have only troubles with the [Lolin C3-Mini](https://github.com/arendst/Tasmota/discussions/15443) and Tasmota. **Every!** other C3 board does work well. After we modified the HF part of the board we got it going more or less good. There is "somewhere" a bug in the HF board design.
Arduino core is NOT the problem!

**Comment by XFer012** [comment]
You mean it scans OK, correctly detects RSSI, but cannot connect?

**Comment by Sys64736** [comment]
@Jason2866 is right, there is a flaw in the design.  You need to set the transmit power to -8.5db right after wifi.begin then it will connect.  If using the softAP, you need to set it after starting also.
```
     WiFi.begin(ssid_char, password_char); 
     WiFi.setTxPower(WIFI_POWER_8_5dBm);
 ```

**Comment by Jason2866** [comment]
The antenna matching is not correct. So the HF signal gets reflected. A really bad workaround is to reduce transmit power so the reflecting is reduced and does not eliminate the (weak) signal completly. A real fix needs changes in the HF matching network.

**Comment by Sys64736** [comment]
Yes, it's a bad workaround and although it eliminates the AUTH_EXPIRE response it's deceiving because the board's RX'd signal will be much greater than the TX range.   I bought a bunch of these boards when they first came out and have used many successfully but only within ~10 meters of the AP, after that RX strength is still pretty good but too many dropped packets on the TX end.  I only use them now with SoftAP as it only needs to transmit to a mobile phone which is usually within a few meters of the device.   Hoping they improve the design and release an updated version of the board.

**Comment by XFer012** [comment]
> @Jason2866 is right, there is a flaw in the design. You need to set the transmit power to -8.5db right after wifi.begin then it will connect. If using the softAP, you need to set it after starting also.
> 
> ```
>      WiFi.begin(ssid_char, password_char); 
>      WiFi.setTxPower(WIFI_POWER_8_5dBm);
> ```

Thank you, I will try this workaround. Better than nothing!

**Comment by XFer012** [comment]
Confirmed working. Thanks!

**Comment by VojtechBartoska** [comment]
Closing as solved, if needed, you can reopen the issue.

**Comment by gauthier12** [comment]
Hi. 
If someone somewhere search it, same problem with the "banana pi BPI-Centi-S3" and the same workaround works
Thanks @Sys64736

**Comment by gauthier12** [comment]
Hi. 
If someone somewhere search it, same problem with the "banana pi BPI-Centi-S3" and the same workaround works
Thanks @Sys64736

**Comment by fbernaly** [comment]
> @Jason2866 is right, there is a flaw in the design. You need to set the transmit power to -8.5db right after wifi.begin then it will connect. If using the softAP, you need to set it after starting also.
> 
> ```
>      WiFi.begin(ssid_char, password_char); 
>      WiFi.setTxPower(WIFI_POWER_8_5dBm);
> ```

That workaround also worked for me!

**Comment by unmateria** [comment]
> > @Jason2866 is right, there is a flaw in the design. You need to set the transmit power to -8.5db right after wifi.begin then it will connect. If using the softAP, you need to set it after starting also.
> > ```
> >      WiFi.begin(ssid_char, password_char); 
> >      WiFi.setTxPower(WIFI_POWER_8_5dBm);
> > ```
> 
> Thank you, I will try this workaround. Better than nothing!

Thank you! it worked perfectly :)

**Comment by totial** [comment]
Had the same problem and after trying MULTIPLE HW changes like adding capacitors, diodes to boost 3.3v to 3.4v, and modifying the smd wifi antenna I decided to try all esp32c3 super mini  boards from a batch of 10 I bought and found out that 4 out of 10 where unable to connect to wifi reporting error AUTH_EXPIRE. Exactly the same sketch (wifi tx power 8.5db) for all of them. My conclusion is the manufacturer doesnt chack for defectives and sells all of them. Dont know what other issues can arise. Hope this helps (to discard the broken ones).

**Comment by Jason2866** [comment]
@totial You are right. There are bad designed (defective) C3 out there and sold.
Even well known names had problematic C3 boards design. Just to mention one.
Lolin. The did not really inform the users. Just the "fix" to lower the TX power was published.
The did a redesign of the C3 enhancing rev. number. The new rev. does not need the "fix" anymore.
To be 100% clear. Every C3 board which does need lowering TX power is a defective board!!

**Comment by Slayingripper** [comment]
> @Jason2866 is right, there is a flaw in the design. You need to set the transmit power to -8.5db right after wifi.begin then it will connect. If using the softAP, you need to set it after starting also.
> 
> ```
>      WiFi.begin(ssid_char, password_char); 
>      WiFi.setTxPower(WIFI_POWER_8_5dBm);
> ```

This solved my issue! I was going at it for hours and could not for the life of me figure out why it wasn't connecting!

**Comment by DansDesigns** [comment]
> [@Jason2866](https://github.com/Jason2866) is right, there is a flaw in the design. You need to set the transmit power to -8.5db right after wifi.begin then it will connect. If using the softAP, you need to set it after starting also.
> 
> ```
>      WiFi.begin(ssid_char, password_char); 
>      WiFi.setTxPower(WIFI_POWER_8_5dBm);
> ```

Thank you so much, this solved a weeks worth of useless messing around in code!

Confirmed working on ESP32-S3 Devkit with ESP32-S3-WROOM-1

**Comment by Jason2866** [comment]
@DansDesigns First time i hear about issues with S3 in "classic" devkit form factor.
Good to know there are bad build clones here too.

**Comment by parzibyte** [comment]
Hi. Maybe it's a little obvious but I tried every solution listed here and at the end it was solved by restarting the router. I am connected through a repeater, so I restarted both the main router and the repeater, then everything worked well:
[  1090][D][WiFiGeneric.cpp:1040] _eventCallback(): Arduino Event: 4 - STA_CONNECTED

By the way, this is the code I am using, but the esp32 only connected after tried this code and restarting the router. I am using ESP32 S3 WROOM N16R8 with camera (maybe it's a clone because it does not have any psram).

```cpp
    WiFi.mode(WIFI_STA);
    WiFi.disconnect(true, true);
    delay(100);
    wl_status_t resultado = WiFi.begin("ssid", "password");
    Serial.printf("Result code %d", resultado);
    WiFi.setTxPower(WIFI_POWER_8_5dBm);

    while (WiFi.status() != WL_CONNECTED)
    {
        delay(300);
        Serial.print(".");
    }
```

My **platformio.ini** looks like this:

```ini
; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_size = 16MB
board_build.psram = enabled
lib_deps = 
	esp32async/AsyncTCP@^3.3.6
	esp32async/ESPAsyncWebServer@^3.7.2
	;witnessmenow/UniversalTelegramBot@^1.3.0

build_flags = -DCORE_DEBUG_LEVEL=5 -DDEBUG_ESP_SSL

```

**Comment by shawrhit** [comment]
> @Jason2866 is right, there is a flaw in the design.  You need to set the transmit power to -8.5db right after wifi.begin then it will connect.  If using the softAP, you need to set it after starting also.
> ```
>      WiFi.begin(ssid_char, password_char); 
>      WiFi.setTxPower(WIFI_POWER_8_5dBm);
>  ```        

4 years and this problem still persists, only way is lowering the wifi power to -8.5dBm, thank for the solution, it works!

**Comment by rubensmacielgomes** [comment]
Estava com este mesmo problema e encontrei o vilão deste pequeno notável esp32-c3. Depois de muito tempo, resolvi tirar os pinos que soldei na placa para melhorar a conexão na protoboard. Estes pinos cria um ruido ou sujeira na comunicação com o wifi ou bluetooth. Depois de retirados ou cortado o excesso dos pinos, voltou a funcionar perfeitamente a comunicação com wi-fi.

<img width="336" height="387" alt="Image" src="https://github.com/user-attachments/assets/c432868d-14f7-44e4-9766-a6bf05b874ad" />

<img width="299" height="337" alt="Image" src="https://github.com/user-attachments/assets/4937d286-37a2-4a29-b05a-1a8162a97ab1" />


Ficou desta maneira e funcionou perfeitamente com o app rainmaker/alexa, sem precisar incluir código para melhorar a conexão com wifi.

<img width="278" height="259" alt="Image" src="https://github.com/user-attachments/assets/9a11a230-f569-49ba-b929-a9945ef47daa" />
